name: Unzip and Deploy

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Find latest zip
        run: |
          ZIP_FILE=$(ls -t *.zip | head -n 1)
          echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV

      - name: Unzip project
        run: |
          unzip -o "$ZIP_FILE" -d .
        env:
          ZIP_FILE: ${{ env.ZIP_FILE }}

      - name: Remove zip
        run: rm -f *.zip

      - name: Commit unzipped files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzipped and deployed latest project" || echo "No changes"
          git push
