name: Unzip site.zip and deploy
on:
  push:
    paths:
      - "site.zip"      # run when you upload/replace site.zip
    branches:
      - main
  workflow_dispatch:     # allow manual run from Actions tab

permissions:
  contents: write        # allow the workflow to commit back

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure unzip is available
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Clean repo except the zip and .git
        run: |
          shopt -s extglob
          rm -rf !(site.zip|.git|.github)

      - name: Unzip site.zip into repo root
        run: unzip -o site.zip -d .

      - name: Remove the zip
        run: rm -f site.zip

      - name: Commit & push changes
        run: |
          git config user.name "mosaic-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "deploy: unpack site.zip"
          git push
